const SPEC_ALIASES: Record<string, string> = {
  'screen size': 'Display',
  screen: 'Display',
  display: 'Display',
  'display size': 'Display',
  'display type': 'Display',
  'screen type': 'Display',
  brightness: 'Display',
  resolution: 'Resolution',
  'aspect ratio': 'Aspect ratio',
  'screen surface description': 'Screen surface',
  'display resolution maximum': 'Resolution',
  processor: 'Processor',
  cpu: 'Processor',
  'cpu model': 'Processor',
  'cpu family': 'Processor',
  'processor type': 'Processor',
  'processor brand': 'Processor',
  'processor model': 'Processor',
  'processor speed': 'Processor',
  graphics: 'Graphics',
  'graphics card': 'Graphics',
  'graphics card description': 'Graphics',
  gpu: 'Graphics',
  'graphics coprocessor': 'Graphics',
  'graphics co-processor': 'Graphics',
  'video card': 'Graphics',
  'graphics ram': 'Graphics',
  'graphics memory type': 'Graphics',
  ram: 'RAM',
  memory: 'RAM',
  'ram memory installed size': 'RAM',
  'memory installed size': 'RAM',
  'installed ram': 'RAM',
  'memory size': 'RAM',
  'memory capacity': 'RAM',
  'system memory': 'RAM',
  'system ram': 'RAM',
  'total ram': 'RAM',
  storage: 'Storage',
  'hard disk size': 'Storage',
  'hard drive': 'Storage',
  'hard drive size': 'Storage',
  'ssd capacity': 'Storage',
  'solid state drive capacity': 'Storage',
  'memory storage capacity': 'Storage',
  'flash memory size': 'Storage',
  'hard disk capacity': 'Storage',
  'storage capacity': 'Storage',
  'internal storage': 'Storage',
  'operating system': 'Operating system',
  'operating system version': 'Operating system',
  os: 'Operating system',
  'os version': 'Operating system',
  weight: 'Weight',
  'item weight': 'Weight',
  'product weight': 'Weight',
  'package weight': 'Weight',
  'battery life': 'Battery life',
  battery: 'Battery life',
  'battery capacity': 'Battery life',
  'battery average life': 'Battery life',
  'connectivity technology': 'Connectivity',
  connectivity: 'Connectivity',
  wireless: 'Connectivity',
  'wireless communication standard': 'Connectivity',
  'wireless communication technology': 'Connectivity',
  bluetooth: 'Connectivity',
  'bluetooth technology': 'Connectivity',
  'bluetooth standard': 'Connectivity',
  'connector type': 'Connector',
  ports: 'Ports',
  'usb ports': 'Ports',
  'total usb ports': 'Ports',
  warranty: 'Warranty',
  'warranty type': 'Warranty',
  wattage: 'Power',
  'output wattage': 'Power',
  'input voltage': 'Voltage',
  voltage: 'Voltage',
  'input current': 'Voltage',
  'product dimensions': 'Dimensions',
  dimensions: 'Dimensions',
  'item dimensions l x w x h': 'Dimensions',
  colour: 'Colour',
  color: 'Colour',
  material: 'Material',
  'base material': 'Material',
  capacity: 'Capacity',
};

const DROP_SPEC_LABELS = new Set([
  'model',
  'model name',
  'model number',
  'brand',
  'style',
  'theme',
  'finish type',
  'pattern',
  'package information',
  'included components',
  'net quantity',
  'language',
  'age range (description)',
  'special feature',
  'compatible devices',
  'compatible phone models',
  'recommended uses for product',
  'specific uses for product',
  'form factor',
  'movement detection technology',
  'tab cut',
  'sensor type',
  'cable type',
  'mounting type',
  'sheet size',
  'pages',
  'writing instrument form',
  'ink colour',
  'ink color',
  'bulb base',
  'lamp type',
  'coffee maker type',
  'battery cell composition',
]);

export const CANONICAL_SPEC_ORDER = [
  'Display',
  'Resolution',
  'Processor',
  'Graphics',
  'RAM',
  'Storage',
  'Operating system',
  'Weight',
  'Battery life',
  'Connectivity',
  'Camera',
  'Water resistance',
  'Charging',
  'Power',
  'Capacity',
  'Material',
  'Colour',
  'Dimensions',
  'Ports',
  'Connector',
  'Voltage',
  'Output voltage',
  'Output current',
  'Warranty',
];

export function normalizeSpecLabel(label: string): string {
  const key = label.trim().toLowerCase();
  return SPEC_ALIASES[key] ?? label.trim();
}

export function isDroppedSpecLabel(label: string): boolean {
  return DROP_SPEC_LABELS.has(label.trim().toLowerCase());
}